global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'apigateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8087']

  - job_name: 'config-server'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8890']

  - job_name: 'eureka'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8761']

  - job_name: 'users'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8090']

  - job_name: 'forum'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8085']

  - job_name: 'messaging'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8086']

  - job_name: 'courses'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8091']

  - job_name: 'quiz'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8088']

  - job_name: 'exams'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8092']

  - job_name: 'adaptive-learning'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8093']

  - job_name: 'ai-assistant-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8094']

  - job_name: 'privetcours'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8095']
