spring.application.name=eureka
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
management.prometheus.metrics.export.enabled=true
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
